### ISSUE TITLE
Certificate Error Occurs When Associating Desktop Application With Microsoft Partner Center

### ISSUE THREAD

**Issue by ghost** [microsoft/DiceWeb#8]
## Definition Of The Problem 

I have the components specified in the [documen](https://docs.microsoft.com/tr-tr/samples/microsoft/diceweb/sample-partner-center-apps-uwp-cpp/)t for testing applications: 

- Microsoft Visual Studio Community 2019 (Version 16.8.4)
-  Windows 10 SDK (Version 2004 - 10.0.19041.0) - `SignTool.exe`
- Microsoft Partner Center Account (Individual Account)

However, I'm having a certificate problem while associating the application with Microsoft Partner Center via Visual Studio IDE. 

## Steps Followed

The steps I follow in associating the desktop application with the Microsoft Partner Center are as follows:

- Cloning of the project from the [remote repository](https://github.com/microsoft/DiceWeb.git).
- The opening of the project solution (`DiceWebSampleApps_vs2019.sln`) in Visual Studio IDE. 
- Downloading the signable file (`SignableFile.bin`) from the Microsoft Partner Center.
- Calling `SignTool.exe` from the command line to sign the file. Since `SignTool.exe` takes a PFX file as an argument, I used the certificate generation tool on the Visual Studio IDE. I copied the PFX file to the directory where the `SignTool.exe` tool will be run. 

(1) I opened a certificate selection window on Visual Studio IDE.

<p align="center"> 
  <img width=484" height="317"
  src="https://user-images.githubusercontent.com/57282885/106132442-02255100-6175-11eb-93d7-d55953d747a1.png"
</p>

<div align="center">
     Image 1: Visual Studio IDE Certificate Selection Window
</div>

(2) I clicked the "Create" button to create a new certificate.

<p align="center"> 
  <img width=301" height="226"
  src="https://user-images.githubusercontent.com/57282885/106132453-03ef1480-6175-11eb-99cf-721cac5a72df.png"
</p>

<div align="center">
     Image 2: Create New Certificate
</div>

(3) I created a new certificate. I uploaded the certificate (*.pfx file) created in the current directory.

<p align="center"> 
  <img width=300" height="220"
  src="https://user-images.githubusercontent.com/57282885/106132460-05b8d800-6175-11eb-974d-41ea9f92c369.png"
</p>

<div align="center">
     Image 3: Choose A New Certificate
</div>

(4) I chose the new certificate created.

<p align="center"> 
  <img width=483" height="188"
  src="https://user-images.githubusercontent.com/57282885/106132463-06ea0500-6175-11eb-8fae-4b6f028941b4.png"
</p>

<div align="center">
     Image 4: Viewing The New Certificate
</div>

- I called the `SignTool.exe` tool from the command line to mark the `SignableFile.bin` file. When I ran the command I thought everything was fine. 

```powershell 
.\signtool.exe sign /f .\<company_name>.pfx /p <password> /v .\SignableFile.bin
```

<p align="center"> 
  <img width=683" height="120"
  src="https://user-images.githubusercontent.com/57282885/106134315-6ba65f00-6177-11eb-8d79-74c31d75c7b9.png"
</p>

<div align="center">
     Image 5: Marking The SignableFile.bin File
</div>

- I ran the following command to verify the marked file. The verification command returned the following error: 

```powershell 
.\signtool.exe verify /a .\SignableFile.bin
```

<p align="center"> 
  <img width=349" height="69"
  src="https://user-images.githubusercontent.com/57282885/106134740-07d06600-6178-11eb-83c9-0f2a15e92b1d.png"
</p>

<div align="center">
     Image 6: Marking The SignableFile.bin File
</div>

- I got the following error when I tried to drag the SignableFile.bin file, which was marked ignoring the verification error, to the Microsoft Partner Center:

<p align="center"> 
  <img width=683" height="348"
  src="https://user-images.githubusercontent.com/57282885/106135214-aa88e480-6178-11eb-8f63-480ca6a6fcb9.png"
</p>

<div align="center">
     Image 7: Error Warning Shown On Microsoft Partner Center
</div>

## Help Request 

I don't know enough about certificate management in Windows 10. Therefore, I tried many methods but couldn't be successful. The `SignTool.exe` tool and Microsoft Partner Center generated similar errors. I tried using the `X.509` key pair, which is short-term and reliable to run. But the Root Certificate Manager gave the same error.

I think this might be because I'm an individual user. What can I do to fix this problem?

**Comment by sercansebetci** [comment]
I learned that the cause of this problem is that the file signed using the certificate I created in my locak area isn't valid in other systems. This issue is resolved if the certificate is signed by a trusted CA (Certificate Authority). That is why I decided to close the issue.

**Comment by ghost** [comment]
I learned that the cause of this problem is that the file signed using the certificate I created in my local area isn't valid in other systems. This issue is resolved if the certificate is signed by a trusted CA (Certificate Authority). That is why I decided to close the issue.
